# Admin server
server.address=0.0.0.0
server.port=18083

# Managed jmqx node list: name=baseUrl, separated by comma
jmqx.admin.nodes=local=http://127.0.0.1:28083/api/admin
jmqx.admin.nodeTimeoutMs=2000

# Frontend static files
jmqx.admin.frontend.integrated=true
jmqx.admin.frontend.buildOnStart=false
jmqx.admin.frontend.build.workDir=jmqx-admin/frontend
jmqx.admin.frontend.build.command=npm run build
jmqx.admin.frontend.distDir=jmqx-admin/frontend/dist
spring.web.resources.static-locations=classpath:/static/,file:jmqx-admin/frontend/dist/
